@startuml
actor ЛечащийВрач
ЛечащийВрач -> Система: Установить статус

Система -> Система: Запросить ввести статус
ЛечащийВрач -> Система: Ввести статус

Система -> ДанныеОПациенте: Обновить статус

ДанныеОПациенте --> Система: Возврат
Система --> ЛечащийВрач: Возврат
@enduml
