@startuml
actor Пациент

Пациент -> Система: Нажать SOS

Система -> ДанныеОПациенте: Получить данные пациента
ДанныеОПациенте --> Система: Возврат

actor ЛечащийВрач
Система -> ЛечащийВрач: Отправить сигнал с данными

@enduml
