@startuml
actor ЛечащийВрач
ЛечащийВрач -> Система: Добавить анализ

Система -> Система: Запросить ввести название и время анализа.
ЛечащийВрач -> Система: Ввести название и время

Система -> ДанныеОПациенте: Добавить анализ

ДанныеОПациенте --> Система: Возврат
Система --> ЛечащийВрач: Возврат
@enduml
