@startuml
actor ЛечащийВрач
ЛечащийВрач -> Система: Установить диагноз

Система -> Система: Запросить ввести диагноз
ЛечащийВрач -> Система: Ввести диагноз


Система -> Система: Запросить показ пациенту
ЛечащийВрач -> Система: Ввести решение о показе

Система -> ДанныеОПациенте: Добавить диагноз

ДанныеОПациенте --> Система: Возврат
Система --> ЛечащийВрач: Возврат
@enduml
