@startuml
class Приложение <<injector>>, <<main>>
{
+Создать() : void
}
Приложение ..> ЭкранВхода : <<create>>
Приложение ..> ЭкранВрача : <<create>>
Приложение ..> ЭкранПациента : <<create>>
Приложение ..> Вход : <<create>>
Приложение ..> Врач : <<create>>
Приложение ..> Пациент : <<create>>
Приложение ..> Пациенты : <<create>>

class ЭкранВхода <<UI>>{
+id

+считатьИндидуальныйКод(код : int) void
}
ЭкранВхода "1"-->"1, +id" Вход
ЭкранВхода "+id" o-- ЭкранВрача
ЭкранВхода "+id" o-- ЭкранПациента


class ЭкранВрача <<UI>> {
+id : int
+idТекущегоПациента : int

+отобразитьГлавныйЭкран() : void
+считатьПациента() : int
+считатьСтатус() : str
+считатьАнализ() : str
+считатьДиагноз() : str
+отобразитьУведомление() : void
-сохранить() : void
}

ЭкранВрача "1"-->"n,id" Врач
ЭкранВрача ..> Пациенты : <<use>>



class ЭкранПациента <<UI>>
{
+id : int

+отобразитьГлавныйЭкран() : void
+отобразитьРасписание() : void
+отобразитьАнализ() : void
+отобразитьДиагноз() : void
+отправитьУведомление() : void
}

ЭкранПациента "1"-->"n, +id" Пациент
ЭкранПациента ..> Пациенты : <<use>>


class Вход
{
+ поискПользователя(id) : object
+ переходНаГлавныйЭкран()
}
Вход ..> Пациенты : <<use>>
Вход "+id" o--  Врач
Вход "+id" o-- Пациент



class Врач
{
+ id : int
+ уведомление : bool

+найтиДанные() : List<str>
+ изменитьСтатус(idТекущегоПациента : int, статус : str)
+ изменитьАнализ(idТекущегоПациента : int, анализ : str)
+ изменитьДиагноз(idТекущегоПациента : int, диагноз : str)
+ получитьУведомление(idПациента : int) : List<str>
}
Врач "n"-->"1, +id" Пациенты

class Пациент
{
+ id : int

-найтиВрача() : int
+найтиДанные() : List<str>
+отправитьУведомление(idВрача : int) : void
}
Пациент "n"-->"1,+id" Пациенты
Пациент ..> Уведомление : <<create>>

class Уведомление
{
+idПациента
+idВрача

-собратьИнформацию() : List<str>
+отправитьВрачу(List<str>) : void
}
Уведомление "n"-->"1,+id" Врач

class Пациенты
{
+idПациента : List <int>
+ФИОпациента : List <str>
+Палата : List <int>
+Статус : List <str>
+Анализ : List <str>
+Диагноз : List <str>
+idВрача : List <int>
+ФИОВрача
}
@enduml
