@startuml
class Приложение <<injector>>, <<main>>
{
+Создать() : void
}

Приложение ..> ЭкранПациентаРасширение : <<create>>
Приложение ..> Переводчик : <<create>>
Приложение ..> ЭкранПереводчик : <<create>>
Приложение ..> ЭкранПациента : <<create>>

class ЭкранПациента <<UI>>
{
}

class ЭкранПациентаРасширение <<UI>> #back:lightblue
{
+отобразитьПереводчик() : void
}
ЭкранПациентаРасширение "1" -->"1," ЭкранПереводчик
ЭкранПациента <|-- ЭкранПациентаРасширение

class ЭкранПереводчик <<UI>> #back:lightblue
{
+считатьТекс(текст : string) : void
+отобразитьПеревод() : void
}
ЭкранПереводчик "1" <--> "1, +текст" Переводчик

class Переводчик #back:lightblue
{
-списокСловарей Dict <str: <List <Словарь>>
-язык : str
+текущийТекст : str
+перевод : str

+определитьЯзык() : str
+перевестиТекст() : str
}

class Словарь #back:lightblue
{
+словаНаРусском : str
+переводы : str
}
Переводчик  o--  Словарь 
@enduml
