@startuml
class Приложение <<injector>>, <<main>>
{
+Создать() : void
}
Приложение ..> ЭкранВрача : <<create>>
Приложение ..> ЭкранВрачаРасширение : <<create>>
Приложение ..> ЭкранПациентаРасширение : <<create>>
Приложение ..> ВрачРасширение : <<create>>
Приложение ..> ПациентРасширение : <<create>>
Приложение ..> ЭкранПациента : <<create>>
Приложение ..> Врач : <<create>>
Приложение ..> Пациент : <<create>>


class ЭкранВрачаРасширение <<UI>> #back:lightblue
{
+считатьАнализИОтправитьУведомление():str
}

ЭкранВрачаРасширение "1"-->"n,id" ВрачРасширение


class ЭкранПациентаРасширение <<UI>> #back:lightblue
{
+отобразитьУведомление(анализ : str) : void
}

ЭкранПациентаРасширение "1"<-->"n, +id" ПациентРасширение


class ВрачРасширение #back:lightblue
{
+изменитьАнализИОтправитьУведомление (idТекущегоПациента : int, анализ : str) : void
}
ВрачРасширение "1"-->"n, +анализ" ПациентРасширение

class ПациентРасширение #back:lightblue
{
+получитьУведомление(анализ : str) : void
}



class ЭкранПациента  <<UI>>
{

}

class ЭкранВрача  <<UI>>
{
}
ЭкранПациента  <|-- ЭкранПациентаРасширение
Врач <|-- ВрачРасширение
Пациент <|-- ПациентРасширение
ЭкранВрача <|-- ЭкранВрачаРасширение
@enduml
