@startuml
class Приложение <<injector>>, <<main>>
{
+Создать() : void
}

Приложение ..> ЭкранПациентаРасширение : <<create>>
Приложение ..> ЭкранПациента : <<create>>

class ЭкранПациента <<UI>>
{

}
ЭкранПациента <|-- ЭкранПациентаРасширение

class ЭкранПациентаРасширение <<UI>> #lightblue
{
+отобразитьГлавныйЭкранРуссский() : void
+отобразитьГлавныйЭкранАнглийский() : void
}
ЭкранПациентаРасширение ..> НастройкиЭкранaПациента : <<use>>

class НастройкиЭкранaПациента #lightblue
{
+именаИконокРусский : List<str>
+именаИконокАнглийский : List<str>

}
@enduml
